USE [master]
GO

/****** Object:  Database [Hastane Proje]    Script Date: 2.06.2023 14:34:18 ******/
CREATE DATABASE [Hastane Proje]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hastane Proje', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Hastane Proje.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Hastane Proje_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Hastane Proje_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hastane Proje].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hastane Proje] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hastane Proje] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hastane Proje] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hastane Proje] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hastane Proje] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hastane Proje] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hastane Proje] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hastane Proje] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hastane Proje] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hastane Proje] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hastane Proje] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hastane Proje] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hastane Proje] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hastane Proje] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hastane Proje] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hastane Proje] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hastane Proje] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hastane Proje] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hastane Proje] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hastane Proje] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hastane Proje] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hastane Proje] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hastane Proje] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Hastane Proje] SET  MULTI_USER 
GO

ALTER DATABASE [Hastane Proje] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hastane Proje] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hastane Proje] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hastane Proje] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Hastane Proje] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Hastane Proje] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Hastane Proje] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Hastane Proje] SET  READ_WRITE 
GO

